# Generated by Django 2.2.6 on 2020-05-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.CharField(max_length=10),
        ),
    ]
